package jchess.view;

import jchess.model.MoveHistoryModel;

import javax.swing.*;
import java.awt.*;

/*
* All moves which was taken by current player will be displayed in the table generated by this class
* it a view for Move History class.
* */

public class MoveHistoryView {

    public JScrollPane scrollPane;
    public JTable table;

    public MoveHistoryView(MoveHistoryModel model){

        this.table = new JTable(model);
        this.scrollPane = new JScrollPane(this.table);
        this.scrollPane.setMaximumSize(new Dimension(100, 100));
        this.table.setMinimumSize(new Dimension(100, 100));
        this.scrollPane.setAutoscrolls(true);
    }
}
